FROM ubuntu

ENV DEBIAN_FRONTEND=noninteractive

# Install necessary packages 
RUN apt-get update && apt-get install
RUN apt-get install -y python3-opencv \
                       python3-pip \
                       python3-dev \
		       python3-numpy \
                       python3-setuptools

# Install paho mqtt to send messages to cloud
RUN pip3 install paho-mqtt

WORKDIR /data/w251/hw3

ENTRYPOINT [ "python3" ]
CMD ["facesave.py"]
